# video_pref=worst
# show_thumbnails=1
search_region=US
fancy_subs=1
async_thumbnails=1
is_loop=1
thumbnail_quality=medium
thumbnail_viewer=kitty
fzf_preview_side=right
ytdl_pref="worst+bestaudio/best"
