-- muestra popup con atajos de teclado disponibles
return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    init = function()
        vim.o.timeout = true
        vim.o.timeoutlen = 300
    end,
    opts = {
        disable = {
            buftypes = {},
            filetypes = { "dbui" },
        },
        plugins = {
            presets = {
                operators = false,
                motions = false,
                text_objects = false,
                windows = false,
                nav = false,
                z = false,
                g = false,
            },
        },
        layout = { align = "center" },
        filter = function(mapping)
            return mapping.desc and mapping.desc ~= ""
        end,
        spec = {
            { "<leader>b", ":Telescope buffers<cr>", desc = "buffers  " },
            { "<leader>c", group = "código  " },
            { "<leader>ca", ":Lspsaga code_action<cr>", desc = "acción" },
            { "<leader>cf", ":Lspsaga finder<cr>", desc = "finder" },
            { "<leader>cg", ":Telescope live_grep<cr>", desc = "buscar texto en archivos" },
            { "<leader>ch", group = "Jerarquia llamadas  " },
            { "<leader>chi", ":Lspsaga incoming_calls<cr>", desc = "entrante  " },
            { "<leader>cho", ":Lspsaga outgoing_calls<cr>", desc = "saliente  " },
            { "<leader>cn", ":enew<cr>", desc = "nuevo archivo" },
            { "<leader>co", ":Lspsaga outline<cr>", desc = "abrir/cerrar outline" },
            { "<leader>cp", ":Lspsaga peek_definition<cr>", desc = "ver definición (float)" },
            { "<leader>cs", ":Telescope lsp_document_symbols<cr>", desc = "Document Symbols" },
            { "<leader>f", ":Telescope find_files<cr>", desc = "econtrar 󰈞 " },
            { "<leader>g", ":Telescope live_grep<cr>", desc = "grep  " },
            { "<leader>h", ":Telescope oldfiles<cr>", desc = "historial  " },
            { "<leader>i", group = "git 󰊢 " },
            { "<leader>ia", ":G add .<cr>", desc = "add (todo)" },
            { "<leader>ib", ":Gitsigns blame_line<cr>", desc = "ver quien realizó cambio en esa línea" },
            { "<leader>ic", ":G commit<cr>", desc = "commit" },
            { "<leader>id", ":G diff<cr>", desc = "diff" },
            { "<leader>ie", ":G restore --staged .<cr>", desc = "restore (todo)" },
            { "<leader>ih", group = "hunk (cambios)" },
            { "<leader>ihn", ":Gitsigns next_hunk<cr>", desc = "siguiente cambio" },
            { "<leader>ihp", ":Gitsigns prev_hunk<cr>", desc = "cambio anterior" },
            { "<leader>ihr", ":Gitsigns reset_hunk<cr>", desc = "revertir cambio" },
            { "<leader>ihv", ":Gitsigns preview_hunk<cr>", desc = "previsualizar cambio" },
            { "<leader>il", ":G pull origin main<cr>", desc = "pull (origin/main)" },
            { "<leader>io", ":G log<cr>", desc = "log" },
            { "<leader>ip", ":G push origin main<cr>", desc = "push (origin/main)" },
            { "<leader>is", ":Git <cr>", desc = "Panel" },
            { "<leader>n", group = "siguiente" },
            { "<leader>nc", ":Gitsigns next_hunk<cr>", desc = "cambio" },
            { "<leader>nd", ":Lspsaga diagnostic_jump_next<cr>", desc = "diagnostico" },
            { "<leader>o", ":Telescope lsp_document_symbols<cr>", desc = "outline (symbols)" },
            { "<leader>p", group = "anterior" },
            { "<leader>pc", ":Gitsigns prev_hunk<cr>", desc = "cambio" },
            { "<leader>pd", ":Lspsaga diagnostic_jump_prev<cr>", desc = "diagnostico" },
            { "<leader>r", group = "ejecutar código  " },
            { "<leader>ro", ":w<cr>:!go run %<cr>", desc = "golang" },
            { "<leader>s", ":Telescope lsp_document_symbols<cr>", desc = "lsp symbols  " },
            { "<leader>t", ":Telescope colorscheme<cr>", desc = "color  " },
        },
    },
}
